version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user/testEngine/codeDeploy
permissions:
  - object: /home/ec2-user/testEngine/codeDeploy
    pattern: "*.sh"
    mode: 777
hooks:
  BeforeInstall:
    - location: beforeInstall.sh
      timeout: 300
  AfterInstall:
    - location: afterInstall.sh     
      timeout: 3600